name: manifest-hash
on:
  workflow_dispatch:
  push:
    paths:
      - 'exhibits/TRACE_EPOCH_2025_Q3_Exhibit_A_Hash_Manifest.txt'
jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Locate Exhibit A
        id: find
        run: |
          set -euo pipefail
          FILE="$(git ls-files '*Exhibit_A_Hash_Manifest.txt' | head -n1 || true)"
          if [ -z "$FILE" ]; then
            echo "::error ::Exhibit A manifest not found in repo"
            ls -la
            exit 1
          fi
          echo "file=$FILE" >> "$GITHUB_OUTPUT"
          echo "Using: $FILE"
      - name: Compute SHA256 of Exhibit A
        run: |
          set -e
          FILE="${{ steps.find.outputs.file }}"
          sha256sum "$FILE" | tee manifest.sha256
          HASH="$(cut -d' ' -f1 manifest.sha256)"
          echo "::notice title=SHA256(manifest)::${HASH}"
  
